name: Gatsby Publish

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: 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
					deploy-branch: master